id: IEABB2A00
source: https://www.lotsawahouse.org
source_file: null
initial_creation_type: input
imported: '2022-06-15T20:14:16.527210'
last_modified: '2022-06-15T20:14:16.527221'
parser: null
source_metadata:
  title: Vajrāyudha
  language: en
  description: 'Texts by the master Vajrāyudha/Vajraśastra (rdo rje mtshon cha):'
  volume:
    f4872:
      title: The Praise to Mañjuśrī—Glorious Wisdom's Excellent Qualities
      base_file: f4872.txt
      order: 1
      parent: Mañjuśrī
    fA47A:
      title: The Praise to Mañjuśrī—Glorious Wisdom's Excellent Qualities
      base_file: fA47A.txt
      order: 2
      parent: Mañjuśrī
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
